//Local
GET http://localhost:7071/api/dboSHOWSVW/
Content-Type: application/json

//Prod
//GET https://retrieve-shows-api.azurewebsites.net/api/dboSHOWSVW?code=CKOkkqeUupOwOU-BkV4x5bIVDdG93kNzsxbCTRVpskYbAzFumMZhKw%3D%3D/